-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tasks
(
    id bigserial NOT NULL,
    title character varying(300) NOT NULL,
    description text,
    category_id bigint,
    status task_status,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    priority priority_level DEFAULT 'MEDIUM',
    PRIMARY KEY (id)
);

COMMENT ON TABLE public.tasks
    IS '-- Tasks table
-- Central table storing all tasks created by users.
-- References auxiliary tables for priority, category, frequency, and status.
-- Includes scheduling details such as start date/time and expected duration.';


CREATE TABLE IF NOT EXISTS public.categories
(
    id bigserial NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    PRIMARY KEY (id),
    CONSTRAINT category_name UNIQUE (name)
);

COMMENT ON TABLE public.categories
    IS '-- Categories table
-- Defines categories to classify tasks (e.g., School, Work, Personal, Home).
-- Helps organize tasks into meaningful groups.';


CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    name character varying(300) NOT NULL,
    email character varying(300) NOT NULL,
    password_hash character varying(300),
    provider_id bigint,
    external_uid character varying(300),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT provider_externalid_unique UNIQUE (provider_id, external_uid)
);

COMMENT ON TABLE public.users
    IS '-- Users table
-- Stores information about system users who create and manage tasks.
-- Each user can be assigned tasks and interact with them.';

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigserial NOT NULL,
    name character varying(50) NOT NULL,
    description text,
    PRIMARY KEY (id),
    CONSTRAINT role_name UNIQUE (name)
);

COMMENT ON TABLE public.roles
    IS '-- Roles table
-- Defines user roles within the system (e.g., Admin, Member, Guest).
-- Useful for access control and permission management.';

CREATE TABLE IF NOT EXISTS public.roles_users
(
    users_id bigserial NOT NULL,
    roles_id bigserial NOT NULL,
    PRIMARY KEY (users_id, roles_id)
);

CREATE TABLE IF NOT EXISTS public.tasks_users
(
    tasks_id bigserial NOT NULL,
    users_id bigserial NOT NULL,
    PRIMARY KEY (tasks_id, users_id)
);

CREATE TABLE IF NOT EXISTS public.auth_providers
(
    id bigserial NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT auth_name UNIQUE (name)
);

COMMENT ON TABLE public.auth_providers
    IS '-- Authentication providers
-- Google, GitHub, etc.';

CREATE TABLE IF NOT EXISTS public.task_schedules
(
    id bigserial NOT NULL,
    task_id bigint NOT NULL,
    frequency frequency_type NOT NULL,
    times_per_week integer,
    days_of_week integer[],
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.task_instances
(
    id bigserial NOT NULL,
    task_id bigint NOT NULL,
    scheduled_date date NOT NULL,
    completed_date timestamp with time zone,
    status task_status,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tasks
    ADD FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (provider_id)
    REFERENCES public.auth_providers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_users
    ADD FOREIGN KEY (users_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_users
    ADD FOREIGN KEY (roles_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks_users
    ADD FOREIGN KEY (tasks_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks_users
    ADD FOREIGN KEY (users_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.task_schedules
    ADD FOREIGN KEY (task_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.task_instances
    ADD FOREIGN KEY (task_id)
    REFERENCES public.tasks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;